//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.BusinessName = new HashSet<BusinessName>();
        }
    
        public int ID { get; set; }
        public string Branchname { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> Country_id { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessName> BusinessName { get; set; }
    }
}
