//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessName
    {
        public int ID { get; set; }
        public string BusinessName1 { get; set; }
        public string Logo { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> BusinessType_id { get; set; }
        public Nullable<int> Branch_id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual BusinessType BusinessType { get; set; }
    }
}
